# Generated by Django 4.2.6 on 2024-03-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hr",
            name="department",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="hr",
            name="joined_data",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
