# Generated by Django 4.2.6 on 2024-03-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_hr_department_hr_joined_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="hr", name="name",),
        migrations.RemoveField(model_name="hr", name="phone",),
    ]
