# Generated by Django 4.2.6 on 2024-03-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_remove_hr_name_remove_hr_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="status",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
